[package]
name = "matrix"
version = "0.1.0"
authors = ["wingdust <995315823@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
